version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'WeCare'
      MYSQL_USER: 'ryednap'
      MYSQL_PASSWORD: 'unico'
      MYSQL_ROOT_PASSWORD: 'ultimo'
    ports:
      - '3306:3306'
    expose:
      # open port 3306 open the container
      - '3306'
    #data gets deleted after container exits or breaks specify the location to persist
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mysql:
    driver: local
